config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#home"

    get 'pages/about', to: 'pages#about'
    get 'pages/privacy_policy', to: 'pages#privacy_policy'
    get 'pages/profile', to: 'pages#profile'
    get 'pages/comments_demonstration', to: 'pages#comments_demonstration'

    get 'admin/index', to: 'admin#index'
    get 'admin/show', to: 'admin#show'
    delete 'admin/destroy', to: 'admin#destroy'
    delete 'admin/destroy_log', to: 'admin#destroy_log'

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations' }

    resources :pet_projects, only: [:index, :show]
    resources :comments, except: [:show] do
      resources :replies, except: [:index, :new, :show]
    end
  end

  match '*path', to: 'application#not_found_route', via: :all
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :text, presence: true, length: { minimum: 1 }
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment!, only: [:create, :edit, :update, :destroy]
  before_action :set_reply!, only: [:edit, :update, :destroy]
  before_action :authorize_reply!
  after_action :verify_authorized

  def create
    @reply = @comment.replies.build(reply_params)
    @reply.user = current_user
    if @reply.save

      if current_user.admin?
        notify_user @comment.user
      else
        notify_admin
      end

      respond_to do |format|
        format.html do
          flash[:notice] = t("controllers.replies.create.success")
          redirect_to comments_path
        end

        format.turbo_stream do
          flash.now[:notice] = t("controllers.replies.create.success")
        end
      end
    else
      flash[:alert] = "Reply was not created."
      redirect_to comments_path
    end
  end

  def edit
  end

  def update
    if @reply.update(reply_params)
      respond_to do |format|
        format.html do
          flash[:notice] = t("controllers.replies.update.success")
          redirect_to comments_path
        end

        format.turbo_stream do
          flash.now[:notice] = t("controllers.replies.update.success")
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reply.destroy

    respond_to do |format|
      format.html do
        flash[:notice] = t("controllers.replies.destroy.success")
        redirect_to comments_path
      end

      format.turbo_stream do
        flash.now[:notice] = t("controllers.replies.destroy.success")
      end
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:text)
  end

  def set_reply!
    @reply = @comment.replies.find(params[:id])
  end

  def set_comment!
    @comment = Comment.find(params[:comment_id])
  end

  def authorize_reply!
    authorize(@reply || Reply)
  end
end

app/views/replies/_form.html.erb
<%= form_with model: [comment, reply] do |f| %>
  <%= render 'shared/errors', object: reply %>

  <%= f.text_area :text, autofocus: true %>
  <%= f.submit t("buttons.save"), class: params[:action] == "edit" ? "button_small" : "button_micro" %>
<% end %>

app/views/replies/_reply.html.erb
<div class="reply__title">
  <%= gravatar(reply.user, '', 22) %>
  <h3><%= reply.user.name_or_email %></h3>
</div>
<div class="reply__body">
  <div class="reply__text"><%= simple_format(reply.text) %></div>
  <div class="reply__links">
    <%= link_to edit_comment_reply_path(comment, reply), class: "button_micro" do %>
      <%= render "components/comments/edit_button" %>
    <% end %>
    <%= link_to comment_reply_path(comment, reply), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button_micro" do %>
      <%= render "components/comments/delete_button" %>
    <% end %>
  </div>
</div>

app/views/replies/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id @comment}_replies" do %>
  <%= turbo_frame_tag @reply, data: { controller: "scroll" } do %>
    <li class="reply">
      <%= render "replies/reply", comment: @comment, reply: @reply %>
    </li>
  <% end %>
<% end %>

<%= append_flash %>

app/views/replies/destroy.turbo_stream.erb
<%= turbo_stream.remove @reply %>

<%= append_flash %>

app/views/replies/edit.html.erb
<main class="reply_edit">
  <%= link_to t("buttons.back"), comments_path, class: "button reply_edit__button" %>
  <h1 class="reply_edit__title">Edit reply</h1>
  <%= turbo_frame_tag @reply do %>
    <div class="reply_edit__body">
      <% if request.headers["Turbo-Frame"].present? %>
        <%= link_to t("buttons.close"), comments_path, class: "button_small comments__close_button" %>
      <% end %>
      <%= render "form", comment: @comment, reply: @reply %>
    </div>
  <% end %>
</main>

app/views/replies/update.turbo_stream.erb
<%= turbo_stream.replace @reply do %>
  <%= turbo_frame_tag @reply do %>
    <li class="reply">
      <%= render "replies/reply", comment: @comment, reply: @reply %>
    </li>
  <% end %>
<% end %>

<%= append_flash %>