config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#home"

    get 'pages/about', to: 'pages#about'
    get 'pages/privacy_policy', to: 'pages#privacy_policy'
    get 'pages/profile', to: 'pages#profile'
    get 'pages/comments_demonstration', to: 'pages#comments_demonstration'

    get 'admin/index', to: 'admin#index'
    get 'admin/show', to: 'admin#show'
    delete 'admin/destroy', to: 'admin#destroy'
    delete 'admin/destroy_log', to: 'admin#destroy_log'

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations' }

    resources :pet_projects, only: [:index, :show]
    resources :comments, except: [:show] do
      resources :replies, except: [:index, :new, :show]
    end
  end

  match '*path', to: 'application#not_found_route', via: :all
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy

  validates :text, presence: true, length: { minimum: 1 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment!, only: [:edit, :update, :destroy]
  before_action :authorize_comment!
  after_action :verify_authorized

  def index
    @comments = current_user.comments.includes(:replies)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      notify_admin

      respond_to do |format|
        format.html do
          flash[:notice] = t("controllers.comments.create.success")
          redirect_to comments_path
        end

        format.turbo_stream do
          flash.now[:notice] = t("controllers.comments.create.success")
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.html do
          flash[:notice] = t("controllers.comments.update.success")
          redirect_to comments_path
        end

        format.turbo_stream do
          flash.now[:notice] = t("controllers.comments.update.success")
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html do
        flash[:notice] = t("controllers.comments.destroy.success")
        redirect_to comments_path
      end

      format.turbo_stream do
        flash.now[:notice] = t("controllers.comments.destroy.success")
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_comment!
    @comment = Comment.find(params[:id])
  end

  def authorize_comment!
    authorize(@comment || Comment)
  end
end

app/views/comments/_comment.html.erb
<div class="comment__title">
  <%= gravatar(comment.user, '', 25) %>
  <h2><%= comment.user.name_or_email %></h2>
</div>
<div class="comment__body">
  <div class="comment__text"><%= simple_format(comment.text) %></div>
  <div class="comment__links">
    <%= link_to edit_comment_path(comment), class: "button_micro" do %>
      <%= render "components/comments/edit_button" %>
    <% end %>
    <%= link_to comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button_micro" do %>
      <%= render "components/comments/delete_button" %>
    <% end %>
  </div>
</div>


<div class="replies" data-controller="replies">
  <ul id="<%= dom_id comment %>_replies">
    <% comment.replies.each do |reply| %>
      <%= turbo_frame_tag reply do %>
        <li class="reply">
          <%= render "replies/reply", comment: comment, reply: reply %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <button class="replies__button button_small" data-action="replies#show">
    <span><%= t("buttons.add_reply") %></span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
    </svg>
  </button>

  <div class="replies__form" data-replies-target="form">
    <%= render "replies/form", comment: comment, reply: comment.replies.build %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment do |f| %>
  <%= render 'shared/errors', object: comment %>

  <%= f.text_area :text, autofocus: true %>
  <%= f.submit t("buttons.save"), class: "button_small" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append 'comments' do %>
  <%= turbo_frame_tag @comment, data: { controller: "scroll" } do %>
    <li class="comment"><%= render @comment %></li>
  <% end %>
<% end %>

<%= turbo_stream.replace Comment.new do %>
  <%= turbo_frame_tag Comment.new %>
<% end %>

<%= append_flash %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

<%= append_flash %>

app/views/comments/edit.html.erb
<main class="comment_edit">
  <%= link_to t("buttons.back"), comments_path, class: "button comment_edit__button" %>
  <h1 class="comment_edit__title">Edit comment</h1>
  <%= turbo_frame_tag @comment do %>
    <div class="comment_edit__body">
      <% if request.headers["Turbo-Frame"].present? %>
        <%= link_to t("buttons.close"), comments_path, class: "button_small comments__close_button" %>
      <% end %>
      <%= render "form", comment: @comment %>
    </div>
  <% end %>
</main>

app/views/comments/index.html.erb
<% provide :current_page_tab_title, current_page_tab_title(t("header.comments")) %>
<%= render partial: "shared/header", locals: { current_page: t("header.comments") } %>

<main class="comments">
  <div class="comments__title">
    <h1><%= t(".title") %></h1>
    <p><%= t(".text") %></p>
  </div>
  <div class="comments__body">
    <%= link_to t("buttons.create_comment"), new_comment_path, class: "comments__button button", data: {turbo_frame: dom_id(Comment.new)} %>
    <%= turbo_frame_tag Comment.new %>
    <ul class="comments__list" id="comments">
      <% @comments.each do |comment| %>
        <%= turbo_frame_tag comment do %>
          <li class="comment"><%= render comment %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</main>

<%= render partial: "shared/footer" %>

app/views/comments/new.html.erb
<main class="comment_new">
  <%= link_to t("buttons.back"), comments_path, class: "button comment_new__button" %>
  <h1 class="comment_new__title">New comment</h1>
  <%= turbo_frame_tag Comment.new do %>
    <div class="comment_new__body">
      <% if request.headers["Turbo-Frame"].present? %>
        <%= link_to t("buttons.close"), comments_path, class: "button_small comments__close_button" %>
      <% end %>
      <%= render "form", comment: @comment %>
    </div>
  <% end %>
</main>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace @comment do %>
  <%= turbo_frame_tag @comment do %>
    <li class="comment"><%= render @comment %></li>
  <% end %>
<% end %>

<%= append_flash %>