config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#home"

    get 'pages/about', to: 'pages#about'
    get 'pages/privacy_policy', to: 'pages#privacy_policy'
    get 'pages/profile', to: 'pages#profile'
    get 'pages/comments_demonstration', to: 'pages#comments_demonstration'

    get 'admin/index', to: 'admin#index'
    get 'admin/show', to: 'admin#show'
    delete 'admin/destroy', to: 'admin#destroy'
    delete 'admin/destroy_log', to: 'admin#destroy_log'

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations' }

    resources :pet_projects, only: [:index, :show]
    resources :comments, except: [:show] do
      resources :replies, except: [:index, :new, :show]
    end
  end

  match '*path', to: 'application#not_found_route', via: :all
end

app/views/admin/index.html.erb
<% provide :current_page_tab_title, current_page_tab_title(t("header.admin")) %>
<%= render partial: "shared/header", locals: { current_page: t("header.admin") } %>

<main class="admin_users">
  <div class="admin_users__sidekiq_link">
    <%= link_to "Sidekiq::Web", "/sidekiq", target: "_blank", class: "button_micro" %>
  </div>
  <ul class="users_list">
    <li>
      <div class="users_list__email">email:</div>
      <div class="users_list__name">name:</div>
      <div class="users_list__provider">provider:</div>
      <div class="users_list__role">role:</div>
      <div class="users_list__time">created_at:</div>
      <div class="users_list__links">links:</div>
    </li>
    <% @users.each do |user| %>
      <li>
        <div class="users_list__email"><%= user.email %></div>
        <div class="users_list__name"><%= user.name %></div>
        <div class="users_list__provider"><%= user.provider || "nil" %></div>
        <div class="users_list__role"><%= user.role %></div>
        <div class="users_list__time"><%= user.created_at.to_formatted_s(:short) %></div>
        <div class="users_list__links">
          <%= link_to "Show", admin_show_path(id: user.id), class: "button_micro" %>
          <%= link_to "Delete", admin_destroy_path(id: user.id), class: "button_micro", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </li>
    <% end %>
  </ul>
  <ul class="logs_list">
    <li>
      <div>email:</div>
      <div>ip_address:</div>
      <div>count:</div>
    </li>
    <% @logs.each do |log| %>
      <li>
        <div><%= log.user&.email || "nil" %></div>
        <div><%= log.ip_address || "nil" %></div>
        <div><%= log.request_count %></div>
        <%= link_to "Delete", admin_destroy_log_path(id: log.id), class: "button_micro", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </li>
    <% end %>
  </ul>
</main>