config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#home"

    get 'pages/about', to: 'pages#about'
    get 'pages/privacy_policy', to: 'pages#privacy_policy'
    get 'pages/profile', to: 'pages#profile'
    get 'pages/comments_demonstration', to: 'pages#comments_demonstration'

    get 'admin/index', to: 'admin#index'
    get 'admin/show', to: 'admin#show'
    delete 'admin/destroy', to: 'admin#destroy'
    delete 'admin/destroy_log', to: 'admin#destroy_log'

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations' }

    resources :pet_projects, only: [:index, :show]
    resources :comments, except: [:show] do
      resources :replies, except: [:index, :new, :show]
    end
  end

  match '*path', to: 'application#not_found_route', via: :all
end

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any? %>
  <div class="form_errors" data-controller="notificationsErrors">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" data-action="notificationsErrors#close">&times;</button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <a href="https://github.com/ghstd">Github</a>
</footer>

app/views/shared/_header.html.erb
<header class="header" data-controller="navigation">
  <button class="header__nav_button button_small" data-action="navigation#show">Navigation</button>
  <div class="header__nav_container">
    <nav class="header__navigation">
      <%= nav_link t("header.home"), root_path, current_page: current_page %>
      <%= nav_link t("header.projects"), pet_projects_path, current_page: current_page %>
      <%= nav_link t("header.about"), pages_about_path, current_page: current_page %>

      <% if user_signed_in? %>
        <%= nav_link t("header.comments"), comments_path, current_page: current_page %>
      <% else %>
        <%= nav_link t("header.comments"), pages_comments_demonstration_path, current_page: current_page %>
      <% end %>

      <% if user_signed_in? && current_user.admin? %>
        <%= nav_link t("header.admin"), admin_index_path, current_page: current_page %>
      <% end %>
    </nav>

    <ul class="header__controls">
      <li class="theme_switcher" data-controller="theme">
        <%= render "components/theme/theme_switcher" %>
      </li>
      <li class="lang_switcher" data-controller="lang">
        <%= render "components/lang/lang_switcher" %>
      </li>
    </ul>
  </div>

  <% if user_signed_in? %>
    <div class="header_login">
      <span><%= current_user.name_or_email %></span>
      <%= gravatar(current_user) %>
    </div>
  <% else %>
    <div class="header_login"><%= link_to t("header.login"), new_user_session_path %></div>
  <% end %>

  <div class="menu_button" data-controller="menuButton">
    <button class="menu_button__title" data-action="menuButton#show">
      <span></span>
      <span></span>
      <span></span>
    </button>
    <div class="menu_button__body">
      <% if user_signed_in? %>
        <%= link_to t("header.profile"), pages_profile_path %>
        <%= link_to t("header.logout"), destroy_user_session_path, data: {turbo_method: :delete} %>
      <% else %>
        <%= link_to t("header.login"), new_user_session_path %>
      <% end %>
    </div>
  </div>
</header>